variables:
  QEMU_DIRECTORY: "/qemu-ubu"
  t: echo $CI_COMMIT_TAG | cut -d'v' -f 2 | cut -d'5' -f 2 | cut -d'.' -f 2
  res: "$t -lt 9"

workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /v([1-9]\[0-9]+\.?[0-9]*|0?5\.(9|[1-9]+[0-9]+)|[0-9]*[6-9])\.?([0-9]+\.?)?/

stages:
    - test

qemu-netty-test:
  stage: test
  script:
    - curl -s https://raw.githubusercontent.com/1Jo1/netty-transport_uring-ci-scripts/netty-kernel-testing/scripts/build-kernel-qemu.sh | bash -s $CI_COMMIT_TAG
    - ls -lah
    - pwd
    - ls -lah netty-incubator-transport-io_uring
    - ls -la netty-incubator-transport-io_uring/target
    - cp netty-incubator-transport-io_uring/target/surefire-reports/TEST-*.xml .
    #- curl -s https://raw.githubusercontent.com/1Jo1/netty-transport_uring-ci-scripts/netty-kernel-testing/scripts/build-kernel.sh | bash -s $CI_COMMIT_TAG
  artifacts:
    when: always
    paths:
      - TEST-*.xml
    reports:
      junit:
        - TEST-*.xml

