variables:
  QEMU_DIRECTORY: "/qemu-ubu"
  t: echo $CI_COMMIT_TAG | cut -d'v' -f 2 | cut -d'5' -f 2 | cut -d'.' -f 2
  res: "$t -lt 9"

workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /v([1-9]\[0-9]+\.?[0-9]*|0?5\.(9|[1-9]+[0-9]+)|[0-9]*[6-9])\.?([0-9]+\.?)?/

stages:
    - build

gcc-kernel-x86:
  stage: build
  script:
    - >
       curl
       -X POST
       -H "Accept: application/vnd.github.v3+json"
       -H "Authorization: token $GITHUB_ACCESS_TOKEN"
       -d "{\"ref\":\"master\", \"inputs\": {\"tag\": \"$CI_COMMIT_TAG\"}}"
       https://api.github.com/repos/1Jo1/github-actions-webhooks/actions/workflows/4579731/dispatches