variables:
  QEMU_DIRECTORY: "/qemu-ubu"
  t: echo $CI_COMMIT_TAG | cut -d'v' -f 2 | cut -d'5' -f 2 | cut -d'.' -f 2
  res: "$t -lt 9"

workflow:
  rules:
    - if: $CI_COMMIT_TAG =~ /v([1-9]\[0-9]+\.?[0-9]*|0?5\.(9|[1-9]+[0-9]+)|[0-9]*[6-9])\.?([0-9]+\.?)?/

stages:
    - qemu-img
    - build-image
    - build-initramfs 
    - testing
    - build-badge

build-qemu-image:
  stage: qemu-img
  script:
    - curl -s https://raw.githubusercontent.com/1Jo1/netty-transport_uring-ci-scripts/netty-kernel-testing/scripts/create-qemu-image.sh | bash -s
  artifacts:
    when: always
    paths:
      - ubuntu.qcow2
      - ubuntu-seed.iso
      - ubuntu-21.04-server-cloudimg-amd64.img

build-kernel-image:
  stage: build-image
  script:
    - wget https://gist.githubusercontent.com/1Jo1/cb1d0dc3ef5b824f5f7db3736d89c688/raw/d88759776bc99787a35784d2cf64f2b7de306425/ubuntu-config
    - mv ubuntu-config .config
    - mkdir kernel-image
    - make olddefconfig
    - make -j24
    - cp arch/x86/boot/bzImage kernel-image/
  artifacts:
    when: always
    paths:
      - kernel-image/
  
build-initramfs:
  stage: build-initramfs
  script:
    - curl -s https://raw.githubusercontent.com/1Jo1/netty-transport_uring-ci-scripts/netty-kernel-testing/scripts/build-initramfs.sh | bash -s
  artifacts:
    when: always
    paths:
      - kernel-image/

netty-tests:
  stage: testing
  script:
    - version=$(make kernelversion)
    - git clone https://github.com/1Jo1/netty-incubator-transport-io_uring.git
    - ls -lha
    - wget https://raw.githubusercontent.com/1Jo1/netty-transport_uring-ci-scripts/netty-kernel-testing/scripts/ubuntu-cloud/user-data
    - wget https://raw.githubusercontent.com/1Jo1/netty-transport_uring-ci-scripts/netty-kernel-testing/scripts/ubuntu-cloud/meta-data
    - rm -rf ubuntu.qcow2 ubuntu-seed.iso
    - wget https://raw.githubusercontent.com/1Jo1/netty-transport_uring-ci-scripts/netty-kernel-testing/scripts/qemu.exp
    - qemu-img create -f qcow2 -b ubuntu-21.04-server-cloudimg-amd64.img ubuntu.qcow2 70G
    - genisoimage -output ubuntu-seed.iso -volid cidata -joliet -rock user-data meta-data
    - expect -f qemu.exp `pwd` ubuntu.qcow2 ubuntu-seed.iso kernel-image/initrd.img-"${version}" kernel-image/bzImage
  after_script:
    - echo $CI_JOB_STATUS > .job_status
  artifacts:
    when: always
    paths:
      - .job_status
      - netty-incubator-transport-io_uring/target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - netty-incubator-transport-io_uring/target/surefire-reports/TEST-*.xml

badge:
  stage: build-badge
  when: always
  script:
    - pip install anybadge
    - cat .job_status
    - wget https://github.com/1Jo1/netty-transport_uring-ci-scripts/raw/netty-kernel-testing/scripts/check-job-status.sh && chmod +x check-job-status.sh
    - ./check-job-status.sh `cat .job_status`
    - wget https://gist.githubusercontent.com/1Jo1/67cde209146fd6fd08869e873974bc69/raw/281900837c2cf00d193168fef9f459fc7b9e7f5f/readme.md
    - wget https://github.com/1Jo1/netty-transport_uring-ci-scripts/raw/netty-kernel-testing/scripts/updateMarkdown && chmod +x updateMarkdown
    - version=$(make kernelversion)
    - ./updateMarkdown $CI_JOB_ID $CI_PIPELINE_ID $version $GITHUB_TOKEN
  artifacts:
    paths:
       - badge.svg
